/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
	theme: {
		extend: {
			colors: {
				primary: "#12171F",
				secondary: {
					DEFAULT: "#35917a",
					100: "#30836e",
					200: "#2a7462",
				},
				black: {
					DEFAULT: "#000",
					100: "#1E1E2D",
					200: "#232533",
				},
				gray: {
					100: "#1B232C",
				},
			},
			fontFamily: {
				sfBlack: ["SF-Pro-Display-Black", "sans-serif"],
				sfBlackItalic: ["SF-Pro-Display-BlackItalic", "sans-serif"],
				sfBold: ["SF-Pro-Display-Bold", "sans-serif"],
				sfBoldItalic: ["SF-Pro-Display-BoldItalic", "sans-serif"],
				sfHeavy: ["SF-Pro-Display-Heavy", "sans-serif"],
				sfHeavyItalic: ["SF-Pro-Display-HeavyItalic", "sans-serif"],
				sfLight: ["SF-Pro-Display-Light", "sans-serif"],
				sfLightItalic: ["SF-Pro-Display-LightItalic", "sans-serif"],
				sfMedium: ["SF-Pro-Display-Medium", "sans-serif"],
				sfMediumItalic: ["SF-Pro-Display-MediumItalic", "sans-serif"],
				sfRegular: ["SF-Pro-Display-Regular", "sans-serif"],
				sfRegularItalic: ["SF-Pro-Display-RegularItalic", "sans-serif"],
				sfSemibold: ["SF-Pro-Display-Semibold", "sans-serif"],
				sfSemiboldItalic: ["SF-Pro-Display-SemiboldItalic", "sans-serif"],
				sfThin: ["SF-Pro-Display-Thin", "sans-serif"],
				sfThinItalic: ["SF-Pro-Display-ThinItalic", "sans-serif"],
				sfUltralight: ["SF-Pro-Display-Ultralight", "sans-serif"],
				sfUltralightItalic: ["SF-Pro-Display-UltralightItalic", "sans-serif"],
				sfTextBlack: ["SF-Pro-Text-Black", "sans-serif"],
				sfTextBlackItalic: ["SF-Pro-Text-BlackItalic", "sans-serif"],
				sfTextBold: ["SF-Pro-Text-Bold", "sans-serif"],
				sfTextBoldItalic: ["SF-Pro-Text-BoldItalic", "sans-serif"],
				sfTextHeavy: ["SF-Pro-Text-Heavy", "sans-serif"],
				sfTextHeavyItalic: ["SF-Pro-Text-HeavyItalic", "sans-serif"],
				sfTextLight: ["SF-Pro-Text-Light", "sans-serif"],
				sfTextLightItalic: ["SF-Pro-Text-LightItalic", "sans-serif"],
				sfTextMedium: ["SF-Pro-Text-Medium", "sans-serif"],
				sfTextMediumItalic: ["SF-Pro-Text-MediumItalic", "sans-serif"],
				sfTextRegular: ["SF-Pro-Text-Regular", "sans-serif"],
				sfTextRegularItalic: ["SF-Pro-Text-RegularItalic", "sans-serif"],
				sfTextSemibold: ["SF-Pro-Text-Semibold", "sans-serif"],
				sfTextSemiboldItalic: ["SF-Pro-Text-SemiboldItalic", "sans-serif"],
				sfTextThin: ["SF-Pro-Text-Thin", "sans-serif"],
				sfTextThinItalic: ["SF-Pro-Text-ThinItalic", "sans-serif"],
				sfTextUltralight: ["SF-Pro-Text-Ultralight", "sans-serif"],
				sfTextUltralightItalic: ["SF-Pro-Text-UltralightItalic", "sans-serif"],
			},
		},
	},
	plugins: [],
};
